version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    networks:
      - demo_springboot-mysql-net
    env_file:
      - .env

    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  server:
    image: myapp
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    networks:
      - demo_springboot-mysql-net
    depends_on:
      mysqldb:
        condition: service_healthy

networks:
  demo_springboot-mysql-net: