<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="ISO-8859-1">
    <link rel="stylesheet" type="text/css" href="/webjars/bootstrap/css/bootstrap.min.css"/>
    <meta charset="UTF-8">
    <title>Technical interview questions.</title>
    <link rel="stylesheet" type="text/css" href="/css/style.x47307.css"/>
    <script type="text/javascript" src="/webjars/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/webjars/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="box-form">
    <div class="left">
        <div class="overlay">
            <h1>Hello World.</h1>
            <span>
			<p>Open your list of questions:</p>
			<a href="/api/v1/questions" id="list_questions_link"><i class="fa fa-twitter" aria-hidden="true"></i>The list of questions</a>
		</span>
        </div>
    </div>
    <div class="right">
        <h5>Login</h5>
        <p>Don't have an account? <a href="#">Creat Your Account</a> it takes less than a minute</p>
        <div class="inputs">
            <input type="text" placeholder="user name">
            <br>
            <input type="password" placeholder="password">
        </div>
        <br><br>

        <div class="remember-me--forget-password">
            <label>
                <input type="checkbox" name="item" checked/>
                <span class="text-checkbox">Remember me</span>
            </label>
            <p>forget password?</p>
        </div>
        <br>
        <button>Login</button>
    </div>
</div>
</body>
</html>
