<!DOCTYPE html>
<head>
    <meta charset="ISO-8859-1">
    <title>Technical interview questions.</title>
    <link rel="stylesheet" type="text/css" href="/webjars/bootstrap/css/bootstrap.min.css"/>
    <script type="text/javascript" src="/webjars/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/webjars/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container text-center">
    <h1>This is default list:</h1>`
    <h3><a href="/api/v1/questions">The list of questions</a></h3>
    <h3><a href="#">Login Page</a></h3>
    <h3><a href="#">Register Page</a></h3>
</div>
</body>
</html>